---
apiVersion: v1
kind: Service
metadata:
  name: to-do-app  # Service name
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "elb"
  labels:
    app: to-do-app  # Label for Service
spec:
  ports:
    - name: http      # Port name
      port: 80        # Port on which the Service listens
      protocol: TCP   # Protocol used
      targetPort: 3000  # Port to forward traffic to in the pods
  selector:
    app: to-do-app    # Selects pods with label 'app: to-do-app'
  type: LoadBalancer   # Exposes the Service
